### ISSUE TITLE
Spruce app Task List view

### ISSUE THREAD

**Issue by moshthepitt** [onaio/kaznet-frontend#14]
- [ ] Make the status field reflect the design
- [ ] Add real XForm title
- [ ] Properly format the time fields
- [ ] Change tests to reflect the above
